開発環境、ドキュメントなどの初期構築
twinkling-gecko/hungry-gecko pull request #1
Opened 2020-07-21 09:43 UTC by s10akir

dockerで開発用コンテナを起動して開発に入れるまでの基盤を整備。
![](https://user-images.githubusercontent.com/34061817/88039006-02b7ac00-cb82-11ea-91c4-d1abe0f98e7e.png)

2020-07-22 08:06 UTC, tatikaze approved these changes

2020-07-22 08:11 UTC, kobar9568 requested changes

2020-07-22 08:11 UTC, kobar9568 commented on README.md
> +
パスワードを空で行けという意味に捉えてしまった
`Password: `にトークンを入れる旨を書くか、
`-p トークン`を指定するか、トークンをパイプする旨を書いてくれるとわかりやすい

2020-07-22 08:11 UTC, kobar9568 commented on src/macksnow/main.go
> +}
インデントスタイルの統一をお願いします

2020-07-23 01:02 UTC, s10akir commented
- [x] gofmtをかけ忘れていた
- [x] pre-commitを外出ししてgofmtがかかるようにした
  - gofmtは異常終了オプションがないっぽいので自動修正、nuxtはスタイル違反があると異常終了でコミット中断という挙動

2020-07-23 01:06 UTC, kobar9568 approved these changes

2020-07-23 04:26 UTC, kobar9568 approved these changes

2020-07-23 06:01 UTC, TAKE1354 approved these changes

2020-07-23 06:01 UTC, merged