Feat/items registration view
twinkling-gecko/hungry-gecko pull request #10
Opened 2020-08-22 11:08 UTC by TAKE1354

2020-08-25 01:35 UTC, kobar9568 commented on src/tangerine/nuxt.config.js
> +    baseURL: 'http://localhost/api/v1/',
ここのハードコーディングが原因で別マシンからのアクセスとかIPでアクセスした時に通信失敗になってる?

2020-08-25 01:36 UTC, s10akir commented on src/tangerine/nuxt.config.js
> +    baseURL: 'http://localhost/api/v1/',
何故これだとIPでアクセスした時に不具合が起こるのかが説明できればマージします
（理由上今解決することはできない）

2020-08-25 02:53 UTC, s10akir requested changes

2020-08-25 02:53 UTC, s10akir commented on src/tangerine/components/GeneralHeader.vue
> +.svg {
命名に汎用的な固有名詞を用いるのは良くない
* このクラスはすべてのsvgに適用されるべきなのか？
* 「svg」という名前からどういうスタイルが適用されるのか想像できるか？
という観点

2020-08-25 02:53 UTC, s10akir commented on src/tangerine/components/GeneralHeader.vue
> +import Gecko from '@/assets/svg/gecko.svg'
わざわざ修正しなくてもいいけど、わざわざ面倒な手続き（パッケージ追加やスタイル定義）をしてまでsvgを用いる理由がない とくにたかが40x40にリサイズしているならなお

2020-08-25 02:53 UTC, s10akir commented on src/tangerine/pages/items/detail/_id.vue
> +  fetchFail = false
fetchFailという命名が状態を表すフラグに対して適切なのか？（私はこれ見て関数だと思った）
あとFailがtrueという状態がヒューマンフレンドリーなのか？（成功が正側で失敗が負側なのでは？負が真とは？）

2020-08-25 02:53 UTC, s10akir commented on src/tangerine/pages/items/index.vue
> +  fetchFail = false
フラグの命名

2020-08-25 02:53 UTC, s10akir commented on src/tangerine/pages/items/index.vue
> +    return (id: any) => {
itemの型定義をちゃんとしてればanyでなくてよいのでは

2020-08-25 02:53 UTC, s10akir commented on src/tangerine/pages/items/new.vue
> +<!--typeScript-->
<script lang="ts"> で自明

2020-08-25 02:53 UTC, s10akir commented on src/tangerine/pages/items/new.vue
> +<!--CSS styleだけだとERRORが起きる-->
???

2020-08-25 02:53 UTC, s10akir commented on src/tangerine/pages/items/new.vue
> +  <div class="A">
???

2020-08-25 02:53 UTC, s10akir commented on src/tangerine/pages/items/new.vue
> +      <p>商品リンク</p>
この辺cssのクラス定義が全く無くない？

2020-08-25 02:53 UTC, s10akir commented on src/tangerine/pages/items/new.vue
> +  deleteForm() {
名詞に見えた（デリートフォームという名前のフォーム）
そもそもデリートではなくクリアでは？

2020-08-25 02:53 UTC, s10akir commented on src/tangerine/pages/items/new.vue
> +  checkSendItem() {
バリデーション？

2020-08-25 02:53 UTC, s10akir commented on src/tangerine/pages/items/index.vue
> +    return (id: any) => {
あと関数ならdoSomeThingの形式を取って命名してほしい気がしなくもない でもヘルパーだからいいのか？

2020-08-25 03:11 UTC, tatikaze commented on src/tangerine/components/GeneralHeader.vue
> +.svg {
リネームします

2020-08-25 03:11 UTC, tatikaze commented on src/tangerine/pages/items/index.vue
> +    return (id: any) => {
computedに関しては名詞であるべきだと思いますが分かりづらいのでリネームします

2020-08-25 04:20 UTC, tatikaze commented on src/tangerine/components/GeneralHeader.vue
> +import Gecko from '@/assets/svg/gecko.svg'
了解。
今回は保留します

2020-08-25 06:05 UTC, kobar9568 commented on src/tangerine/nuxt.config.js
> +    baseURL: 'http://localhost/api/v1/',
さっき話が出たけど、仕様としてコメント入れておいても良いかも

2020-08-25 06:21 UTC, kobar9568 commented on src/tangerine/pages/items/detail/_id.vue
> +  isFetchSuccessed = true
気分の問題だけど、FetchSuccessed とかで良い気もする

2020-08-25 06:38 UTC, kobar9568 commented on src/tangerine/pages/items/new.vue
> +  checkSendItem() {
checkだと曖昧な感じがある

2020-08-26 00:26 UTC, tatikaze approved these changes

2020-08-26 14:49 UTC, s10akir commented on src/tangerine/pages/items/detail/_id.vue
> +      })
失敗時に最も意味を持つエラー内容を握りつぶしてるので、それを保持しておくべきに思う
さらに言えばエラーを保持するフィールドを持っておいて、エラーが存在するか（つまりif err）で表示ロジックの変更にそのまま使えるのでisFetchSuccessedみたいなフラグを定義する必要も無くなりそう

2020-08-27 00:19 UTC, s10akir commented on src/tangerine/pages/items/new.vue
> +  <div class>
class prop不要なので削除

2020-08-27 00:19 UTC, s10akir commented on src/tangerine/pages/items/new.vue
> +  </div>
NITS: formとして作成したほうが（HTML的に）よいかなというのと、するとBootstrapのスタイル適用できるので色々よさ
こちらで巻き取るのでそのままでよいです

2020-08-27 00:19 UTC, s10akir commented on src/tangerine/pages/items/new.vue
> +  }
NITS: フォームにするとHTML5が最初から持ってるバリデーションメソッドが使えるようになる
ここもこちらで巻き取ります

2020-08-27 00:55 UTC, s10akir approved these changes
![](https://user-images.githubusercontent.com/34061817/91371249-6735ed00-e84b-11ea-904c-0c342b651904.png)

2020-08-27 00:56 UTC, kobar9568 approved these changes

2020-08-27 00:57 UTC, merged